### ISSUE TITLE
[1.16.5] When setting Zoom Button on mouse buttons you get stuck on the smooth effect motion.

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#1]
Title^

Can't get it to "untoggle" the smoothing. Works fine on any other key. Not the mosue buttons.

Minecraft: 1.16.5
Forge: 36.1.2
SmoothFocus: 1.2.1

Side note: Also is it possible to set it to zoom only when the button is pressed, then stops zooming when released. Messed around with the config couldn't get it to work like that.

**Comment by paperfour** [comment]
I will start working on this right away! An option to zoom only when the button is pressed, then stop zooming when released is planned.

**Comment by Gbergz** [comment]
Great to hear! I will most likely add this mod to TNP Limitless 3 when that is added.

**Comment by paperfour** [comment]
I'll be sure to let you know when it is all set :D

**Comment by paperfour** [comment]
If you are still here, I've added the feature called "Start at max zoom" and fixed Optifine compatibility issues. Thank you for using SmoothFocus!

**Comment by Gbergz** [comment]
> If you are still here, I've added the feature called "Start at max zoom" and fixed Optifine compatibility issues. Thank you for using SmoothFocus!

Awesome! Thanks for letting me know. Appreciated.
