### ISSUE TITLE
[1.16.5] FOV Effects slider non functional while SmoothFocus is installed.

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#2]
Title^

When the slider is set to 0 there's still FOV effects present. Removing the mod solves this issue.

**MC** 1.16.5
**Forge** 36.1.2
**SmoothFocus** 1.4.0

**Note**
(Reproducable on a clean instance w/ only SmoothFoxus installed.)

**Empty instance without SmoothFocus** (FOV Effects Slider operational.)
https://user-images.githubusercontent.com/26634554/116894728-ae724a00-ac32-11eb-93d7-2f7b457f354b.mp4

**Empty instance with only SmoothFocus** (FOV Effects Slider non-operational.)
https://user-images.githubusercontent.com/26634554/116894757-b5995800-ac32-11eb-9a2a-527c3aec5026.mp4

**Comment by paperfour** [comment]
Interesting, I'll work on this.

**Comment by paperfour** [comment]
fixed in 1.5.0 :)
