### ISSUE TITLE
Scroll wheel zooming doesn't let it zoom all the way in like first zoom does.

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#3]
Title ^

**Video:**
https://streamable.com/iwqzpu 
(After first zoom I try to scroll up to that zoom amount again, which doesn't work. Then again after a bit.)

**Minecraft:** 1.16.5
**Forge:** 36.1.18
**SmoothFocus:** [1.6.0](https://www.curseforge.com/minecraft/mc-mods/smoothfocus/files/3309884)

**Comment by paperfour** [comment]
I was aware of the problem but wasn't sure if anyone would notice it much. I will work on this.

**Comment by paperfour** [comment]
Should be all set now
