### ISSUE TITLE
Smooth camera stays on when the zoom is interrupted.

### ISSUE THREAD

**Issue by DaLumma** [paperfour/SmoothFocus#5]
The smooth camera effect stays on when the zoom is interrupted by opening a UI.
I think there isn't much more I can explain.

But I can say that this is my favourite zoom mod so far, good job👍

**Comment by DaLumma** [comment]
Also here's a video demonstrating it:

https://user-images.githubusercontent.com/51972073/119192164-f7722d00-ba7f-11eb-9421-23ab2b20c8e4.mp4

**Comment by paperfour** [comment]
Thanks for the support, it is fixed in the next beta. Very glad you're utilizing my mod :)
