### ISSUE TITLE
[1.16.5] World disappears around you when Zooming out. (more in desc.)

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#6]
When zooming out, the world around you, the chunks turn invisible until you move the mouse / camera.

### Picture
![image](https://user-images.githubusercontent.com/26634554/119834128-f6b61c80-beff-11eb-852f-d9318307e70e.png)

### Video:
https://streamable.com/4ke5pr

### Versions:
**Forge:** 36.1.18
**Minecraft:** 1.16.5
**SmoothFocus:** 1.6.2

Thanks,
**-** Gbergz

**Comment by paperfour** [comment]
Thanks, this should be an easy fix

**Comment by paperfour** [comment]
1.6.3 fixes this
