### ISSUE TITLE
[1.16.5] SmoothFocus interaction makes MiningGadgets not function, black screen when using the mining gadget.

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#7]
Clean instance, only SmoothFocus & Mining Gadgets installed.

### Reproduce:
1. Grab a Mining Gadget
2. Use it (right click the ground, mine blocks). 
3. Black Screen.
4. Profit?

### Video:
https://user-images.githubusercontent.com/26634554/120351839-7f69f980-c300-11eb-9487-a3ef815c8d50.mp4

### Versions:
- Minecraft: 1.16.5
- Forge: 36.1.18
- SmoothFocus: 1.6.3
- MiningGadgets: 1.7.5

Strange interaction but it boiled down to this mod. Hopefully it's fixable.
**-** Gbergz

**Comment by Gbergz** [comment]
Any updates?

**Comment by paperfour** [comment]
Sorry, I was taking a break for a bit. Will work on this, don't worry.

**Comment by paperfour** [comment]
Resolved in 1.6.4. Also if you don't mind, could you check if it still crashes when run on a server? I think that problem might be fixed.

**Comment by Gbergz** [comment]
Confirmed fixed. Thanks again! 👍
